# Generated by Django 6.1.1 on 2026-09-18 20:36

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[apps.core.validators.validar_cpf]),
        ),
    ]
