# Generated by Django 6.1.1 on 2026-09-21 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_cliente_cpf'),
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('data_hora', models.TimeField()),
                ('duracao', models.PositiveSmallIntegerField(default=50)),
                ('local', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('AGENDADA', 'Agendada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada'), ('REALIZADA', 'Realizada')], default='AGENDADA', max_length=15)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professores.professor')),
            ],
            options={
                'ordering': ['data_hora'],
                'constraints': [models.UniqueConstraint(fields=('professor', 'data_hora'), name='professor_sem_conflito'), models.UniqueConstraint(fields=('local', 'data_hora'), name='local_sem_conflito')],
            },
        ),
    ]
