# Generated by Django 6.1.1 on 2026-09-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='data_hora',
            field=models.DateTimeField(),
        ),
    ]
