# Generated by Django 6.1.1 on 2026-09-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_aula_data_hora'),
        ('clientes', '0002_alter_cliente_cpf'),
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='aula',
            name='professor_sem_conflito',
        ),
        migrations.RemoveConstraint(
            model_name='aula',
            name='local_sem_conflito',
        ),
        migrations.AddConstraint(
            model_name='aula',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELADA'), _negated=True), fields=('professor', 'data_hora'), name='professor_sem_conflito'),
        ),
        migrations.AddConstraint(
            model_name='aula',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELADA'), _negated=True), fields=('local', 'data_hora'), name='local_sem_conflito'),
        ),
    ]
