# Generated by Django 6.1.1 on 2026-09-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_remove_aula_professor_sem_conflito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='telefone_professor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
