# Generated by Django 6.1.1 on 2026-09-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_aula_telefone_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='telefone_professor',
        ),
    ]
