# Generated by Django 6.1.1 on 2026-09-25 16:37

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['nome'], 'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(max_length=255, validators=[apps.core.validators.nomes_sem_caracteres_especiais]),
        ),
        migrations.AlterField(
            model_name='professor',
            name='telefone',
            field=models.CharField(blank=True, max_length=13, null=True, validators=[apps.core.validators.validar_telefone]),
        ),
    ]
